# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import counter_pb2 as counter__pb2


class CounterStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Increment = channel.unary_unary(
                '/Counter/Increment',
                request_serializer=counter__pb2.IncrementRequest.SerializeToString,
                response_deserializer=counter__pb2.IncrementReply.FromString,
                )
        self.GetCounter = channel.unary_unary(
                '/Counter/GetCounter',
                request_serializer=counter__pb2.GetCounterRequest.SerializeToString,
                response_deserializer=counter__pb2.GetCounterReply.FromString,
                )


class CounterServicer(object):
    """Missing associated documentation comment in .proto file."""

    def Increment(self, request, context):
        """Increments the global counter by a certain amount
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetCounter(self, request, context):
        """Get latest counter value
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_CounterServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Increment': grpc.unary_unary_rpc_method_handler(
                    servicer.Increment,
                    request_deserializer=counter__pb2.IncrementRequest.FromString,
                    response_serializer=counter__pb2.IncrementReply.SerializeToString,
            ),
            'GetCounter': grpc.unary_unary_rpc_method_handler(
                    servicer.GetCounter,
                    request_deserializer=counter__pb2.GetCounterRequest.FromString,
                    response_serializer=counter__pb2.GetCounterReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'Counter', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class Counter(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def Increment(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Counter/Increment',
            counter__pb2.IncrementRequest.SerializeToString,
            counter__pb2.IncrementReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetCounter(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/Counter/GetCounter',
            counter__pb2.GetCounterRequest.SerializeToString,
            counter__pb2.GetCounterReply.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
